//
//  YelpConstants.swift
//  Yelp
//
//  Created by Andre Oriani on 2/13/16.
//  Copyright © 2016 Orion. All rights reserved.
//

import Foundation


final class YelpConsts {
    
    private init() {}
    
    enum SortMode: Int {
        case BestMatched = 0, Distance, HighestRated
        static let asArray = [BestMatched, Distance, HighestRated]
        
        func toString() -> String {
            switch self {
                case .BestMatched: return "Best Match"
                case .Distance: return "Distance"
                case .HighestRated: return "Rating"
            }
        }
    }
    
    enum Distance {
        case BestMatch, TwoBlocks, SixBlocks, OneMile, FiveMiles
        
        static let asArray = [BestMatch, TwoBlocks, SixBlocks, OneMile, FiveMiles]
        
        func toString() -> String {
            switch self {
                case .BestMatch: return "Best Match"
                case .TwoBlocks: return "2 Blocks"
                case .SixBlocks: return "6 Blocks"
                case .OneMile: return "1 Mile"
                case .FiveMiles: return "5 Miles"
            }
        }
        
        func meters() -> Int {
            switch self {
                case .BestMatch: return -1
                case .TwoBlocks: return toMeters(fromMiles: NSDecimalNumber(double: 0.2)).integerValue
                case .SixBlocks: return toMeters(fromMiles: NSDecimalNumber(double: 0.6)).integerValue
                case .OneMile: return toMeters(fromMiles: NSDecimalNumber(double: 1.0)).integerValue
                case .FiveMiles: return toMeters(fromMiles: NSDecimalNumber(double: 5.0)).integerValue
            }
        }

    }
    
    static let categoryDict = [
        "Afghan": "afghani",
        "African": "african",
        "American, New": "newamerican",
        "American, Traditional": "tradamerican",
        "Arabian": "arabian",
        "Argentine": "argentine",
        "Armenian": "armenian",
        "Asian Fusion": "asianfusion",
        "Asturian": "asturian",
        "Australian": "australian",
        "Austrian": "austrian",
        "Baguettes": "baguettes",
        "Bangladeshi": "bangladeshi",
        "Barbeque": "bbq",
        "Basque": "basque",
        "Bavarian": "bavarian",
        "Beer Garden": "beergarden",
        "Beer Hall": "beerhall",
        "Beisl": "beisl",
        "Belgian": "belgian",
        "Bistros": "bistros",
        "Black Sea": "blacksea",
        "Brasseries": "brasseries",
        "Brazilian": "brazilian",
        "Breakfast & Brunch": "breakfast_brunch",
        "British": "british",
        "Buffets": "buffets",
        "Bulgarian": "bulgarian",
        "Burgers": "burgers",
        "Burmese": "burmese",
        "Cafes": "cafes",
        "Cafeteria": "cafeteria",
        "Cajun/Creole": "cajun",
        "Cambodian": "cambodian",
        "Canadian": "New)",
        "Canteen": "canteen",
        "Caribbean": "caribbean",
        "Catalan": "catalan",
        "Chech": "chech",
        "Cheesesteaks": "cheesesteaks",
        "Chicken Shop": "chickenshop",
        "Chicken Wings": "chicken_wings",
        "Chilean": "chilean",
        "Chinese": "chinese",
        "Comfort Food": "comfortfood",
        "Corsican": "corsican",
        "Creperies": "creperies",
        "Cuban": "cuban",
        "Curry Sausage": "currysausage",
        "Cypriot": "cypriot",
        "Czech": "czech",
        "Czech/Slovakian": "czechslovakian",
        "Danish": "danish",
        "Delis": "delis",
        "Diners": "diners",
        "Dumplings": "dumplings",
        "Eastern European": "eastern_european",
        "Ethiopian": "ethiopian",
        "Fast Food": "hotdogs",
        "Filipino": "filipino",
        "Fish & Chips": "fishnchips",
        "Fondue": "fondue",
        "Food Court": "food_court",
        "Food Stands": "foodstands",
        "French": "french",
        "French Southwest": "sud_ouest",
        "Galician": "galician",
        "Gastropubs": "gastropubs",
        "Georgian": "georgian",
        "German": "german",
        "Giblets": "giblets",
        "Gluten-Free": "gluten_free",
        "Greek": "greek",
        "Halal": "halal",
        "Hawaiian": "hawaiian",
        "Heuriger": "heuriger",
        "Himalayan/Nepalese": "himalayan",
        "Hong Kong Style Cafe": "hkcafe",
        "Hot Dogs": "hotdog",
        "Hot Pot": "hotpot",
        "Hungarian": "hungarian",
        "Iberian": "iberian",
        "Indian": "indpak",
        "Indonesian": "indonesian",
        "International": "international",
        "Irish": "irish",
        "Island Pub": "island_pub",
        "Israeli": "israeli",
        "Italian": "italian",
        "Japanese": "japanese",
        "Jewish": "jewish",
        "Kebab": "kebab",
        "Korean": "korean",
        "Kosher": "kosher",
        "Kurdish": "kurdish",
        "Laos": "laos",
        "Laotian": "laotian",
        "Latin American": "latin",
        "Live/Raw Food": "raw_food",
        "Lyonnais": "lyonnais",
        "Malaysian": "malaysian",
        "Meatballs": "meatballs",
        "Mediterranean": "mediterranean",
        "Mexican": "mexican",
        "Middle Eastern": "mideastern",
        "Milk Bars": "milkbars",
        "Modern Australian": "modern_australian",
        "Modern European": "modern_european",
        "Mongolian": "mongolian",
        "Moroccan": "moroccan",
        "New Zealand": "newzealand",
        "Night Food": "nightfood",
        "Norcinerie": "norcinerie",
        "Open Sandwiches": "opensandwiches",
        "Oriental": "oriental",
        "Pakistani": "pakistani",
        "Parent Cafes": "eltern_cafes",
        "Parma": "parma",
        "Persian/Iranian": "persian",
        "Peruvian": "peruvian",
        "Pita": "pita",
        "Pizza": "pizza",
        "Polish": "polish",
        "Portuguese": "portuguese",
        "Potatoes": "potatoes",
        "Poutineries": "poutineries",
        "Pub Food": "pubfood",
        "Rice": "riceshop",
        "Romanian": "romanian",
        "Rotisserie Chicken": "rotisserie_chicken",
        "Rumanian": "rumanian",
        "Russian": "russian",
        "Salad": "salad",
        "Sandwiches": "sandwiches",
        "Scandinavian": "scandinavian",
        "Scottish": "scottish",
        "Seafood": "seafood",
        "Serbo Croatian": "serbocroatian",
        "Signature Cuisine": "signature_cuisine",
        "Singaporean": "singaporean",
        "Slovakian": "slovakian",
        "Soul Food": "soulfood",
        "Soup": "soup",
        "Southern": "southern",
        "Spanish": "spanish",
        "Steakhouses": "steak",
        "Sushi Bars": "sushi",
        "Swabian": "swabian",
        "Swedish": "swedish",
        "Swiss Food": "swissfood",
        "Tabernas": "tabernas",
        "Taiwanese": "taiwanese",
        "Tapas Bars": "tapas",
        "Tapas/Small Plates": "tapasmallplates",
        "Tex-Mex": "tex-mex",
        "Thai": "thai",
        "Traditional Norwegian": "norwegian",
        "Traditional Swedish": "traditional_swedish",
        "Trattorie": "trattorie",
        "Turkish": "turkish",
        "Ukrainian": "ukrainian",
        "Uzbek": "uzbek",
        "Vegan": "vegan",
        "Vegetarian": "vegetarian",
        "Venison": "venison",
        "Vietnamese": "vietnamese",
        "Wok": "wok",
        "Wraps": "wraps",
        "Yugoslav": "yugoslav"
    ]

    static let categoryLabels = [
        "Afghan",
        "African",
        "American, New",
        "American, Traditional",
        "Arabian",
        "Argentine",
        "Armenian",
        "Asian Fusion",
        "Asturian",
        "Australian",
        "Austrian",
        "Baguettes",
        "Bangladeshi",
        "Barbeque",
        "Basque",
        "Bavarian",
        "Beer Garden",
        "Beer Hall",
        "Beisl",
        "Belgian",
        "Bistros",
        "Black Sea",
        "Brasseries",
        "Brazilian",
        "Breakfast & Brunch",
        "British",
        "Buffets",
        "Bulgarian",
        "Burgers",
        "Burmese",
        "Cafes",
        "Cafeteria",
        "Cajun/Creole",
        "Cambodian",
        "Canadian",
        "Canteen",
        "Caribbean",
        "Catalan",
        "Chech",
        "Cheesesteaks",
        "Chicken Shop",
        "Chicken Wings",
        "Chilean",
        "Chinese",
        "Comfort Food",
        "Corsican",
        "Creperies",
        "Cuban",
        "Curry Sausage",
        "Cypriot",
        "Czech",
        "Czech/Slovakian",
        "Danish",
        "Delis",
        "Diners",
        "Dumplings",
        "Eastern European",
        "Ethiopian",
        "Fast Food",
        "Filipino",
        "Fish & Chips",
        "Fondue",
        "Food Court",
        "Food Stands",
        "French",
        "French Southwest",
        "Galician",
        "Gastropubs",
        "Georgian",
        "German",
        "Giblets",
        "Gluten-Free",
        "Greek",
        "Halal",
        "Hawaiian",
        "Heuriger",
        "Himalayan/Nepalese",
        "Hong Kong Style Cafe",
        "Hot Dogs",
        "Hot Pot",
        "Hungarian",
        "Iberian",
        "Indian",
        "Indonesian",
        "International",
        "Irish",
        "Island Pub",
        "Israeli",
        "Italian",
        "Japanese",
        "Jewish",
        "Kebab",
        "Korean",
        "Kosher",
        "Kurdish",
        "Laos",
        "Laotian",
        "Latin American",
        "Live/Raw Food",
        "Lyonnais",
        "Malaysian",
        "Meatballs",
        "Mediterranean",
        "Mexican",
        "Middle Eastern",
        "Milk Bars",
        "Modern Australian",
        "Modern European",
        "Mongolian",
        "Moroccan",
        "New Zealand",
        "Night Food",
        "Norcinerie",
        "Open Sandwiches",
        "Oriental",
        "Pakistani",
        "Parent Cafes",
        "Parma",
        "Persian/Iranian",
        "Peruvian",
        "Pita",
        "Pizza",
        "Polish",
        "Portuguese",
        "Potatoes",
        "Poutineries",
        "Pub Food",
        "Rice",
        "Romanian",
        "Rotisserie Chicken",
        "Rumanian",
        "Russian",
        "Salad",
        "Sandwiches",
        "Scandinavian",
        "Scottish",
        "Seafood",
        "Serbo Croatian",
        "Signature Cuisine",
        "Singaporean",
        "Slovakian",
        "Soul Food",
        "Soup",
        "Southern",
        "Spanish",
        "Steakhouses",
        "Sushi Bars",
        "Swabian",
        "Swedish",
        "Swiss Food",
        "Tabernas",
        "Taiwanese",
        "Tapas Bars",
        "Tapas/Small Plates",
        "Tex-Mex",
        "Thai",
        "Traditional Norwegian",
        "Traditional Swedish",
        "Trattorie",
        "Turkish",
        "Ukrainian",
        "Uzbek",
        "Vegan",
        "Vegetarian",
        "Venison",
        "Vietnamese",
        "Wok",
        "Wraps",
        "Yugoslav"
    ]
    
    static let categoryKeys = [
        "afghani",
        "african",
        "newamerican",
        "tradamerican",
        "arabian",
        "argentine",
        "armenian",
        "asianfusion",
        "asturian",
        "australian",
        "austrian",
        "baguettes",
        "bangladeshi",
        "bbq",
        "basque",
        "bavarian",
        "beergarden",
        "beerhall",
        "beisl",
        "belgian",
        "bistros",
        "blacksea",
        "brasseries",
        "brazilian",
        "breakfast_brunch",
        "british",
        "buffets",
        "bulgarian",
        "burgers",
        "burmese",
        "cafes",
        "cafeteria",
        "cajun",
        "cambodian",
        "New)",
        "canteen",
        "caribbean",
        "catalan",
        "chech",
        "cheesesteaks",
        "chickenshop",
        "chicken_wings",
        "chilean",
        "chinese",
        "comfortfood",
        "corsican",
        "creperies",
        "cuban",
        "currysausage",
        "cypriot",
        "czech",
        "czechslovakian",
        "danish",
        "delis",
        "diners",
        "dumplings",
        "eastern_european",
        "ethiopian",
        "hotdogs",
        "filipino",
        "fishnchips",
        "fondue",
        "food_court",
        "foodstands",
        "french",
        "sud_ouest",
        "galician",
        "gastropubs",
        "georgian",
        "german",
        "giblets",
        "gluten_free",
        "greek",
        "halal",
        "hawaiian",
        "heuriger",
        "himalayan",
        "hkcafe",
        "hotdog",
        "hotpot",
        "hungarian",
        "iberian",
        "indpak",
        "indonesian",
        "international",
        "irish",
        "island_pub",
        "israeli",
        "italian",
        "japanese",
        "jewish",
        "kebab",
        "korean",
        "kosher",
        "kurdish",
        "laos",
        "laotian",
        "latin",
        "raw_food",
        "lyonnais",
        "malaysian",
        "meatballs",
        "mediterranean",
        "mexican",
        "mideastern",
        "milkbars",
        "modern_australian",
        "modern_european",
        "mongolian",
        "moroccan",
        "newzealand",
        "nightfood",
        "norcinerie",
        "opensandwiches",
        "oriental",
        "pakistani",
        "eltern_cafes",
        "parma",
        "persian",
        "peruvian",
        "pita",
        "pizza",
        "polish",
        "portuguese",
        "potatoes",
        "poutineries",
        "pubfood",
        "riceshop",
        "romanian",
        "rotisserie_chicken",
        "rumanian",
        "russian",
        "salad",
        "sandwiches",
        "scandinavian",
        "scottish",
        "seafood",
        "serbocroatian",
        "signature_cuisine",
        "singaporean",
        "slovakian",
        "soulfood",
        "soup",
        "southern",
        "spanish",
        "steak",
        "sushi",
        "swabian",
        "swedish",
        "swissfood",
        "tabernas",
        "taiwanese",
        "tapas",
        "tapasmallplates",
        "tex-mex",
        "thai",
        "norwegian",
        "traditional_swedish",
        "trattorie",
        "turkish",
        "ukrainian",
        "uzbek",
        "vegan",
        "vegetarian",
        "venison",
        "vietnamese",
        "wok",
        "wraps",
        "yugoslav"
    ]
    
}